article/urls.py
from django.urls import path
from  . import views

# 正在部署的应用的名称
app_name = 'article'

urlpatterns = [
    # 目前还没有urls
    # 将url映射到视图
    path('article-list/', views.article_list, name='article_list'),
    # <int:id>：Django2.0的path新语法用尖括号<>定义需要传递的参数。这里需要传递名叫id的整数到视图函数中去。
    path('article-detail/<int:id>/',views.article_detail,name='article_detail'),
    # 写文章
    path('article-create/', views.article_create, name='article_create'),
    # 删除文章
    path('article-delete/<int:id>/',views.article_delete,name='article_delete'),
    # 安全删除文章
    path('article-safe-delete/<int:id>/',views.article_safe_delete,name='article_safe_delete'),
    # 更新文章
    path('article-update/<int:id>/', views.article_update, name='article_update'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
# 新增代码，配置app的url
    path('article/', include('article.urls',namespace='article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('password-reset/',include('password_reset.urls')),
    # 评论
    path('comment/', include('comment.urls', namespace='comment')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    # 用户退出
    path('logout/', views.user_logout, name='logout' ),
    # 用户注册
    path('register/', views.user_register,name='register'),
    # 用户删除
    path('delete/<int:id>/', views.user_delete, name='delete'),
    # 用户信息
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

templates/base.html
<!--
    载入静态文件
    模板中要加上 {% load staticfiles %} 之后，才可使用 {% static 'path' %} 引用静态文件
    HTML语法中，所有的内容都被标签包裹；标签及标签中的属性可以对内容进行排印、解释说明等作用。
    <head></head>标签内包含网页的元数据，是不会在页面内显示出来的。<body></body>标签内才是网页会显示的内容。
    留意Bootstrap的css、js文件分别是如何引入的
    jquery.js 和 popper.js 要在 bootstrap.js 前引入。
-->
{% load staticfiles %}

<!-- 网站主语言 -->
<html lang="zh-cn">

<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 预留网站标题的位置 -->
    <title>{% block title %}{% endblock %}</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- 引入monikai.css -->
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">
</head>

<body>
    <!-- 引入导航栏 -->
    {% include 'header.html' %}
    <!-- 预留具体页面的位置 -->
    {% block content %}{% endblock content %}
    <!-- 引入注脚 -->
    {% include 'footer.html' %}
    <!-- bootstrap.js 依赖 jquery.js 和popper.js，因此在这里引入 -->
    <script src="{% static 'jquery/jquery-3.6.0.min.js' %}"></script>
    <!--
        popper.js 采用 cdn 远程引入，意思是你不需要把它下载到本地。
        在实际的开发中推荐静态文件尽量都使用 cdn 的形式。
        采用本地引入是为了让读者了解静态文件本地部署的流程。
    -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1-lts/dist/umd/popper.min.js"></script>
    <!-- 引入layer.js  Layer弹窗组件。-->
    <script src="{% static 'layer/layer.js' %}"></script>
    <!-- 引入bootstrap的js文件 -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

</body>

</html>

templates/footer.html
{% load staticfiles %}
<!-- Footer -->
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white">by Sunlight &copy; 1464316675@qq.com</p>
    </div>
</footer>

templates/header.html
<!-- 定义导航栏
导航栏一般放在页面的顶部。
我们可以使用 .navbar 类来创建一个标准的导航栏，后面紧跟: .navbar-expand-xl|lg|md|sm 类来创建响应式的导航栏 (大屏幕水平铺开，小屏幕垂直堆叠)。
导航栏上的选项可以使用 <ul> 元素并添加 class="navbar-nav" 类。 然后在 <li> 元素上添加 .nav-item 类， <a> 元素上使用 .nav-link 类:
选择.navbar-light用于浅色背景色或.navbar-dark用于深色背景色。然后，使用.bg-*实用程序自定义
-->
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <!--
  当容器在导航栏中时，其横向填充将在低于指定.navbar-expand{-sm|-md|-lg|-xl}类别的断点处移除。
  这可以确保在导航栏折叠时，我们不会在较低视口上不必要地加倍填充。
  -->
  <div class="container">

    <!-- 导航栏图片文字 <img src="/path/to/image.png"></a> 后期加图片的方式 -->
    <a class="navbar-brand" href="#">我的博客</a>

     <!-- 导航入口 -->
    <div>
      <ul class="navbar-nav">
        <!-- 条目 -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'article:article_list' %}">文章</a>
        </li>
        {% if user.is_authenticated %}
        <!-- 如果用户已经登录，则显示用户名下拉框 -->
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ user.username }}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'article:article_create' %}">写文章</a>
              <a class="dropdown-item" href='{% url "userprofile:edit" user.id %}'>个人信息</a>
              <a class="dropdown-item" href='{% url "userprofile:logout" %}'>退出登录</a>
              <a class="dropdown-item" href="#" onclick="user_delete()">删除用户</a>
            </div>
        </li>
    <!-- 如果用户未登录，则显示 “登录” -->
    {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'userprofile:login' %}">登录</a>
        </li>
    <!-- if 语句在这里结束 -->
    {% endif %}
    <!-- 删除用户的JS语句-->
    {% if user.is_authenticated %}
    <form
        style="display:none;"
        id="user_delete"
        action="{% url 'userprofile:delete' user.id %}"
        method="POST"
    >
    {% csrf_token %}
        <button type="submit">发送</button>
    </form>
        <script>
            function user_delete() {
                // 调用layer弹窗组件
                layer.open({
                    title: "确认删除",
                    content: "确认删除用户资料吗？",
                    yes: function(index, layero) {
                        $('form#user_delete button').click();
                        layer.close(index);
                    },
                })
            }
        </script>
    {% endif %}
      </ul>
    </div>

  </div>
</nav>