article/urls.py
from django.urls import path
from  . import views

# 正在部署的应用的名称
app_name = 'article'

urlpatterns = [
    # 目前还没有urls
    # 将url映射到视图
    path('article-list/', views.article_list, name='article_list'),
    # <int:id>：Django2.0的path新语法用尖括号<>定义需要传递的参数。这里需要传递名叫id的整数到视图函数中去。
    path('article-detail/<int:id>/',views.article_detail,name='article_detail'),
    # 写文章
    path('article-create/', views.article_create, name='article_create'),
    # 删除文章
    path('article-delete/<int:id>/',views.article_delete,name='article_delete'),
    # 安全删除文章
    path('article-safe-delete/<int:id>/',views.article_safe_delete,name='article_safe_delete'),
    # 更新文章
    path('article-update/<int:id>/', views.article_update, name='article_update'),
]

comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
    # 发表评论
    path('post-comment/<int:article_id>/', views.post_comment, name='post_comment'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
# 新增代码，配置app的url
    path('article/', include('article.urls',namespace='article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('password-reset/',include('password_reset.urls')),
    # 评论
    path('comment/', include('comment.urls', namespace='comment')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    # 用户退出
    path('logout/', views.user_logout, name='logout' ),
    # 用户注册
    path('register/', views.user_register,name='register'),
    # 用户删除
    path('delete/<int:id>/', views.user_delete, name='delete'),
    # 用户信息
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

article/models.py
from django.db import models
# 导入内建的USER模型
from django.contrib.auth.models import User
# timezone 处理时间有关函数
from django.utils import timezone
from django.urls import reverse
# Create your models here.
# 博客文章数据类型。参数 author title body created updated
class ArticlePost(models.Model):
    # 文章作者。参数 on_delete 用于指定数据删除的方式
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    # 文章标题。models.CharField 为字符串字段，用于保存较短的字符串，比如标题
    title = models.CharField(max_length=100)

    # 文章正文。保存大量文本使用 TextField
    body = models.TextField()

    # 文章创建时间。参数 default=timezone.now 指定其在创建数据时将默认写入当前的时间
    created = models.DateTimeField(default=timezone.now)

    # 文章更新时间。参数 auto_now=True 指定每次数据更新时自动写入当前时间
    updated = models.DateTimeField(auto_now=True)
    # 浏览量
    # PositiveIntegerField是用于存储正整数的字段
    # default=0设定初始值从0开始
    total_views = models.PositiveIntegerField(default=0)
    # 内部类 class Meta 用于给model定义元数据 文章创建时间，负号标识倒序来排列，保证了最新文章永远在最顶部位置
    class Meta:
        #ordering 指定模型返回的数据排列顺序  注意ordering是元组，括号中只含一个元素时不要忘记末尾的逗号
        #-created 倒叙排列
        ordering = ('-created',)
    # 用 _str_ 定义当前调用对象的 s't
    def __str__ (self):
        return self.title

    # 获取文章地址
    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id])

article/forms.py
# 引入表单类
from django import forms
# 引入文章模型
from .models import ArticlePost

# 写文章的表单类
class ArticlePostForm(forms.ModelForm):
    class Meta:
        # 指明数据模型来源
        model = ArticlePost
        # 定义表单包含的字段
        fields = ('title', 'body')

article/views.py
from django.shortcuts import render
# 导入HttpRespond模块
from django.http import HttpResponse
from .models import ArticlePost
import markdown
# 引入redirect重定向模块
from django.shortcuts import render, redirect
# 引入刚才定义的ArticlePostForm表单类
from .forms import ArticlePostForm
# 引入User模型
from django.contrib.auth.models import User
# 引入分页模块
from django.core.paginator import Paginator
# 引入Q对象
from django.db.models import Q
from comment.models import Comment
# Create your views here.
# 视图函数  视图函数中的request与网页发来的请求有关，里面包含get或post的内容、用户浏览器、系统等信息。。
def article_list(request):
    # ArticlePost.objects.all() 可以获得所有的对象（即博客文章），并传递给articles变量
    articles_list = ArticlePost.objects.all()
    search = request.GET.get('search')
    order = request.GET.get('order')
    if search:
        if order == 'total_views':
            article_list = ArticlePost.objects.filter(
                Q(title__icontains=search) |
                Q(body__icontains=search)
            ).order_by('-total_views')
        else:
            article_list = ArticlePost.objects.filter(
                Q(title__icontains=search) |
                Q(body__icontains=search)
            )
    else:
        # 将 search 参数重置为空
        # 用户没有搜索操作，
        # 则search = request.GET.get('search')会使得search = None，
        # 而这个值传递到模板中会错误地转换成"None"字符串
        search = ''
        if order == 'total_views':
            article_list = ArticlePost.objects.all().order_by('-total_views')
        else:
            article_list = ArticlePost.objects.all()
    # 每页显示一篇文章
    paginator = Paginator(articles_list,3)
    # 获取url的页码
    page = request.GET.get('page')
    # 将导航对象页面返回给articles
    articles = paginator.get_page(page)
    # context定义了需要传递给模板的上下文，这里即articles
    # context = {'articles':articles}
    context = {'articles':articles, 'order':order,'search':search}
    # 最后返回了render函数。它的作用是结合模板和上下文，并返回渲染后的HttpResponse对象。
    # request  get或post的内容、用户浏览器、系统等信息
    # article/list.html定义了模板文件的位置、名称
    # context定义了需要传入模板文件的上下文
    # 通俗的讲就是把context的内容，加载进模板，并通过浏览器呈现。
    return render(request,'article/list.html',context)
# 文章详细页 id 这是Django自动生成的用于索引数据表的主键（Primary Key，即pk）
def article_detail(request,id):
    # 获取对应id文章
    article = ArticlePost.objects.get(id=id)
    # 取出文章评论
    comments = Comment.objects.filter(article=id)

    article.total_views += 1
    article.save(update_fields=['total_views'])
    # 将markdown语法渲染成html样式
    # markdown.markdown语法接收两个参数：
    # 第一个参数是需要渲染的文章正文article.body；
    # 第二个参数载入了常用的语法扩展：
    # markdown.extensions.extra中包括了缩写、表格等扩展，
    # markdown.extensions.codehilite则是后面要使用的代码高亮扩展。
    md = markdown.Markdown(
        extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ]
    )
    article.body = md.convert(article.body)
    # 需要传递给模板的对象
    context = {'article':article,'toc':md.toc,'comments':comments}
    #载入模板返回context对象
    return render(request,'article/detail.html',context)
# 文章编辑页
def article_create(request):
    # 判断用户是否提交数据
    if request.method == "POST":
        # 将提交的数据赋值到表单实例中
        article_post_form = ArticlePostForm(data=request.POST)
        # 判断提交的数据是否满足模型的要求
        if article_post_form.is_valid():
            # 保存数据，但暂时不提交到数据库中
            new_article = article_post_form.save(commit=False)
            # 指定数据库中 id=1 的用户为作者
            # 如果你进行过删除数据表的操作，可能会找不到id=1的用户
            # 此时请重新创建用户，并传入此用户的id
            new_article.author = User.objects.get(id=request.user.id)
            # 将新文章保存到数据库中
            new_article.save()
            # 完成后返回到文章列表
            return redirect("article:article_list")
        # 如果数据不合法，返回错误信息
        else:
            return HttpResponse("表单内容有误，请重新填写。")
    # 如果用户请求获取数据
    else:
        # 创建表单类实例
        article_post_form = ArticlePostForm()
        # 赋值上下文
        context = {'article_post_form': article_post_form}
        # 返回模板
        return render(request, 'article/create.html', context)
# 删除文章
def article_delete(request, id):
    # 根据id获取文章
    article = ArticlePost.objects.get(id=id)
    article.user = User.objects.get(id=request.user.id)
    # 调用delete（）方法
    article.delete()
    # 删除后返回list页面
    return redirect("article:article_list")
#凡是重要的数据操作，都应该考虑带有 csrf 令牌的 POST 请求；或者更简单的方法，数据查询用 GET，数据更改用 POST。
def article_safe_delete(request, id):
    if request.method == 'POST':
        article = ArticlePost.objects.get(id=id)
        if request.user != article.author:
            return HttpResponse("抱歉，你无权修改这篇文章。")
        article.delete()
        return redirect("article:article_list")
    else:
        return HttpResponse("仅允许post请求")

# 更新文章
"""
    更新文章的视图函数
    通过POST方法提交表单，更新titile、body字段
    GET方法进入初始表单页面
    id： 文章的 id
"""
def article_update(request ,id):
    # 获取需要修改的文章数据
    article = ArticlePost.objects.get(id=id)
    # 过滤非作者用户
    if request.user != article.author:
        return HttpResponse("抱歉，你无权修改这篇文章~")
    # 判断用户是否为POST提交表单
    if request.method == "POST":
        # 将提交的数据付给表单实例
        article_post_form = ArticlePostForm(data=request.POST)
        # 判断实例是否满足模型要求
        if article_post_form.is_valid():
            # 保存新写入的title和body
            article.title = request.POST['title']
            article.body = request.POST['body']
            article.save()
            # 完成后返回到修改的文章中，要传入id值
            return redirect("article:article_detail",id=id)
        else:
            # 数据不合法就重写
            return HttpResponse("表单内容有误，请重新填写")
    else:
        # 创建表单实例  为update界面的默认值  传入update界面
        article_post_form = ArticlePostForm()
        context = {'article':article,'article_post_from':article_post_form}
        return render(request, 'article/update.html',context)

templates/article/create.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %} {% load staticfiles %}
<!-- 写入 base.html 中定义的 title -->
{% block title %} 写文章 {% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 写文章表单 -->
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <!-- 提交文章的表单 -->
            <form method="post" action=".">
                <!-- Django中需要POST数据的地方都必须有csrf_token -->
                {% csrf_token %}
                <!-- 文章标题 -->
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="title">文章标题</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="title" name="title">
                </div>
                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本区域 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/article/detail.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    文章详情
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 文章详情 -->
<div class="container">
    <div class="row">
        <div class="col-9">
            <!-- 标题及作者 -->
            <h1 class="mt-4 mb-4">{{ article.title }}</h1>
            <div class="alert alert-success">
                <div>
                    作者：{{ article.author }}
                    {% if user == article.author %}
                        <a href="#" onclick="confirm_safe_delete()">删除文章</a>
                        <form
                            style = "display: none;"
                            id="safe_delete"
                            action='{% url "article:article_safe_delete" article.id %}'
                            method="POST"
                            >
                            {% csrf_token %}
                            <button type="submit" >发送</button>
                        </form>
                        <a href="{% url 'article:article_update' article.id %}">编辑文章</a>
                {% endif %}
                </div>
            <div>
                 浏览：{{ article.total_views }}
            </div>
            </div>
            <!-- 文章正文 -->
            <div class="col-12">
            <p>{{ article.body | safe }}</p>
            </div>
            <!-- 发表评论 -->
            <hr>
            {% if user.is_authenticated %}
                <div>
                    <form
                        action="{% url 'comment:post_comment' article.id %}"
                        method="POST"
                    >
                    {% csrf_token %}
                        <div class="form-group">
                            <label for="body">
                                <strong>
                                    我也要发言：
                                </strong>
                            </label>
                            <textarea
                                type="text"
                                class="form-control"
                                id="body"
                                name="body"
                                rows="2"></textarea>
                        </div>
                        <!-- 提交按钮 -->
                        <button type="submit" class="btn btn-primary ">发送</button>
                    </form>
                </div>
                <br>
            {% else %}
                <br>
                <h5 class="row justify-content-center">
                    请<a href="{% url 'userprofile:login' %}">登录</a>后回复
                </h5>
                <br>
            {% endif %}



            <!-- 显示评论 -->
            <h4>共有{{ comments.count }}条评论</h4>
            <div>
                {% for comment in comments %}
                    <hr>
                    <p>
                        <strong style="color: pink">
                            {{ comment.user }}
                        </strong> 于
                        <span style="color: green">
                            {{ comment.created|date:"Y-m-d H:i:s" }}
                        </span> 时说：
                    </p>
                    <pre style="font-family: inherit; font-size: 1em;">{{ comment.body }}</pre>
        {% endfor %}
    </div>
</div>
        <!-- 目录 -->
        <div class="col-3 mt-4" id="sidebar" class="sidebar">
            <div class="sidebar__inner">
                <h4><strong>目录</strong></h4>
                <hr>
                <div>
                    {{ toc|safe }}
                </div>
            </div>
        </div>

    </div>
</div>

<script>
    //删除文章的函数
    function confirm_delete(){
        //调用layer弹窗组件

        layer.open({
            //弹窗标题
            title: "确认删除",
            //正文
            content: "确认删除这篇文章吗？",
            //点击确认后调用回调函数
            yes: function (index,layero){
                //前往指定url
                location.href = '{% url "article:article_delete" article.id %}'
            },
        })
    }

    function confirm_safe_delete(){
        layer.open({
            //弹窗标题
            title: "确认删除",
            //正文
            content: "确认删除这篇文章吗？",
            //点击确认后调用回调函数
            yes: function (index,layero){
                $('form#safe_delete button').click();
                layer.close(index);

            },
        })
    }
</script>

{% endblock content %}

<!--在 article.body 后加上 |safe 过滤器的目的
Django出于安全的考虑，会将输出的HTML代码进行转义，
这使得article.body中渲染的HTML文本无法正常显示。管道符|是Django中过滤器的写法，
而|safe就类似给article.body贴了一个标签，表示这一段字符不需要进行转义了。
<a>标签中增加了onclick属性，表示在点击链接时调用后面的confirm_delete()函数。
confirm_delete()函数中调用了layer弹窗组件，对弹窗的标题、正文以及确定键进行了定义。
location.href是点击确定键后应该前往的地址，即删除文章的url。
通过onclick实现了功能逻辑，因此href链接就不需要再跳转了。
点击删除文章链接时，弹出 layer 弹窗
弹窗不再发起 GET 请求，而是通过 Jquery 选择器找到隐藏的表单，并点击发送按钮
表单发起 POST 请求，并携带了 csrf 令牌，从而避免了 csrf 攻击
-->

templates/article/list.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    首页
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 定义放置文章标题的div容器 -->
<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'article:article_list' %}?search={{ search }}">
                    最新
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'article:article_list' %}?order=total_views&search={{ search }}">
                    最热
                </a>
            </li>
        </ol>
    </nav>
     <!-- 搜索栏 -->
    <div class="row">
        <div class="col-auto mr-auto">
            <form class="form-inline" >
                <label class="sr-only">content</label>
                <input type="text"
                    class="form-control mb-2 mr-sm-2"
                    name="search"
                    placeholder="搜索文章..."
                    required
                >
            </form>
        </div>
    </div>
    <!-- 搜索提示语 -->
    {% if search %}
            {% if articles %}
                <h4><span style="color: green">"{{ search }}"</span>的搜索结果如下：</h4>
                <hr>
            {% else %}
                <h4>暂无<span style="color: green">"{{ search }}"</span>有关的文章。</h4>
                <hr>
            {% endif %}
        {% endif %}

    <div class="row mt-2">
        {% for article in articles %}
        <!-- 文章内容 -->
        <div class="col-4 mb-4">
        <!-- 卡片容器 -->
            <div class="card h-100">
                <!-- 标题 -->
                <h4 class="card-header">{{ article.title }}</h4>
                <!-- 摘要 -->
                <div class="card-body">
                    <p class="card-text">{{ article.body|slice:'100' }}...</p>
                </div>
                <!--
                注脚
                在list.html中，通过href="{% url 'article:article_detail' article.id %}"，将id传递给article/urls.py
                在article/urls.py中，通过<int:id>传递给视图函数article_detail()
                在视图函数article_detail()中，通过形参id取得了文章的id值，并进行处理，最终定位了需要获取的文章对象
                -->
                <div class="card-footer">
                    <a href="{% url 'article:article_detail' article.id %}" class="btn btn-primary">阅读本文</a>
                    <!-- 显示浏览量 -->
                    <span>
                        <small class="col align-self-end" style="color: gray;">
                                浏览: {{ article.total_views }}
                        </small>
                    </span>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>


    <!-- 页码导航 -->
    <div class="pagination row">
        <div class="m-auto">
            <span class="step-links">
                <!-- 如果不是第一页，则显示上翻按钮 -->
                {% if articles.has_previous %}
                    <a href="?page=1&order={{ order }}&search={{ search }}" class="btn btn-success">
                        &laquo; 1
                    </a>
                    <span>...</span>
                    <a href="?page={{ articles.previous_page_number }}&order={{ order }}&search={{ search }}"
                       class="btn btn-secondary"
                    >
                        {{ articles.previous_page_number }}
                    </a>
                {% endif %}

                <!-- 当前页面 -->
                <span class="current btn btn-danger btn-lg">
                    {{ articles.number }}
                </span>

                <!-- 如果不是最末页，则显示下翻按钮 -->
                {% if articles.has_next %}
                    <a href="?page={{ articles.next_page_number }}&order={{ order }}&search={{ search }}"
                       class="btn btn-secondary"
                    >
                        {{ articles.next_page_number }}
                    </a>
                    <span>...</span>
                    <a href="?page={{ articles.paginator.num_pages }}&order={{ order }}&search={{ search }}"
                       class="btn btn-success"
                    >
                        {{ articles.paginator.num_pages }} &raquo;
                    </a>
                {% endif %}
            </span>
        </div>
    </div>
</div>
{% endblock content %}

templates/article/update.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 更新文章 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">文章标题</label>
                    <!-- 在 value 属性中指定文本框的初始值为旧的内容，即 article 对象中的 title 字段 -->
                    <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                </div>
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本域不需要 value 属性，直接在标签体中嵌入数据即可 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12">{{ article.body }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}